**Import Necessary Files**

In [2]:
import pyarrow.parquet as pq
import pandas as pd

**Support Logs**

In [4]:
table = pq.read_table("support_logs_2025-07-01.parquet")
print(table.schema)

timestamp: timestamp[ms]
log_level: string
component: string
ticket_id: string
session_id: string
ip: string
response_time: int64
cpu: double
event_type: string
error: bool
user_agent: string
message: string
debug: string
-- schema metadata --
pandas: '{"index_columns": [], "column_indexes": [], "columns": [{"name":' + 1579

In [6]:
df = pd.read_parquet("support_logs_2025-07-01.parquet")
print(df.dtypes)
print(df.shape)
df.head()

timestamp        datetime64[ms]
log_level                object
component                object
ticket_id                object
session_id               object
ip                       object
response_time             int64
cpu                     float64
event_type               object
error                      bool
user_agent               object
message                  object
debug                    object
dtype: object
(89, 13)

,timestamp,log_level,component,ticket_id,session_id,ip,response_time,cpu,event_type,error,user_agent,message,debug
0,2025-07-01 00:21:00,INFO,careplus.support.GenericService,TCK0701000,sess_TCK0701000,60.130.155.7,1269,27.64,generic_event,False,PostmanRuntime/7.32.2,event for TCK0701000,ℹ️ Logged for monitoring
1,2025-07-01 00:41:00,INFO,careplus.support.GenericService,TCK0701000,sess_TCK0701000,58.36.189.27,1505,57.24,generic_event,False,Mobile-Safari/537.36,event for TCK0701000,ℹ️ Logged for monitoring
2,2025-07-01 01:44:00,DEBUG,careplus.support.GenericService,TCK0701001,sess_TCK0701001,181.18.12.170,586,78.43,generic_event,False,curl/7.68.0,event for TCK0701001,ℹ️ Logged for monitoring
3,2025-07-01 01:49:00,DEBUG,careplus.support.GenericService,TCK0701001,sess_TCK0701001,163.214.94.42,878,63.61,generic_event,False,curl/7.68.0,event for TCK0701001,ℹ️ Logged for monitoring
4,2025-07-01 01:50:00,INFO,careplus.support.GenericService,TCK0701000,sess_TCK0701000,155.68.207.12,1614,87.85,generic_event,False,Python-urllib/3.9,event for TCK0701000,ℹ️ Logged for monitoring

**Support Tickets**

In [7]:
table = pq.read_table("run-1753951545142-part-block-0-r-00000-snappy.parquet")
print(table.schema)

ticket_id: string
created_at: timestamp[ns]
resolved_at: timestamp[ns]
agent: string
priority: string
num_interactions: int32
issue_category: string
channel: string
status: string

In [8]:
df = pd.read_parquet("run-1753951545142-part-block-0-r-00000-snappy.parquet")
print(df.shape)
df.head()

(27, 9)

,ticket_id,created_at,resolved_at,agent,priority,num_interactions,issue_category,channel,status
0,TCK0701000,2025-07-01 00:13:00,NaT,Sneha,Medium,7,Payment Failure,Chat,Open
1,TCK0701001,2025-07-01 01:24:00,2025-07-01 02:47:00,Kavya,Medium,8,Account Locked,Web Form,Resolved
2,TCK0701002,2025-07-01 01:49:00,2025-07-01 19:25:00,Rohit,Low,3,Bug Report,Web Form,Resolved
3,TCK0701004,2025-07-01 03:03:00,2025-07-02 11:00:00,Ananya,High,5,Bug Report,Chat,Resolved
4,TCK0701005,2025-07-01 03:07:00,2025-07-02 00:35:00,Arjun,High,1,Bug Report,Email,Resolved